# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'OkkamiSdkTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for OkkamiSdkTest
  
  #pod 'Moya/RxSwift'
  #pod 'ModelMapper'
  #pod 'Moya-ModelMapper/RxSwift', '4.0.0-beta.3'
  pod 'RxCocoa'
  pod 'RxSwift'
  #pod 'RxOptional'
  pod 'RealmSwift'
  #pod 'SwiftyJSON'
  #pod 'IDZSwiftCommonCrypto', '~> 0.9.0'
  pod 'CryptoSwift'
  pod 'ReachabilitySwift', '~> 3'
  pod 'CocoaAsyncSocket'
  pod 'Log'
  
  target 'OkkamiSdkTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
