# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'RCTOkkamiSdkImplementation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RCTOkkamiSdkImplementation  
  pod 'Moya/RxSwift'
  pod 'ModelMapper'
  pod 'Moya-ModelMapper/RxSwift', '4.0.0-beta.3'
  pod 'RxCocoa'
  pod 'RxOptional'
  pod 'RealmSwift'
  pod 'SwiftyJSON'
  #pod 'IDZSwiftCommonCrypto', '~> 0.9.0'
  pod 'CryptoSwift'
  target 'RCTOkkamiSdkImplementationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
